### ISSUE TITLE
Can you please fix & update build

### ISSUE THREAD

**Issue by Randore** [Neft-io/neft#24]
Hi,
first of all please make the installation process go smooth and easy.
1. sudo npm install -g  neft  
   (worked but why don't you make it easy just like other frameworks npm install -g neft)
2. neft run server or neft run browser or other commands are not working. (showing errors)
3. Make sure you provide an easy to follow tutorial program guide for everyone to try your framework.

This framework is exciting but buggy for a new dev-.

$ neft run browser
/usr/local/lib/node_modules/neft/node_modules/bundle-builder/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:39
          throw err0
          ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/neft/node_modules/bundle-builder/.tmp'
  at Error (native)

**Comment by KrysKruk** [comment]
Hi,

Thank you for this issue.
Can you provide more information about your OS and Node version?

I'll prepare a fixes for that.

**Comment by Randore** [comment]
Mac (iOS) sudo command is only work, how can we exclude writing sudo and entering password each time to run neft commands.

**Comment by KrysKruk** [comment]
Hi @Randore . New Neft version 0.10.2 has been released. Is it fixed now?

**Comment by kleninb** [comment]
@KrysKruk I'll test and let you know.

**Comment by KrysKruk** [comment]
Should be fixed now 😄 
Please create another issue if there is still some problems in installing and building process.
Thanks!
